version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - mkdir -p ${READTHEDOCS_OUTPUT}html/
    - shopt -s extglob dotglob
    - mv !(${READTHEDOCS_OUTPUT}) ${READTHEDOCS_OUTPUT}html/
    - shopt -u dotglob
